# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generated_proto_file.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'generated_proto_file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agenerated_proto_file.proto\"\xda\x01\n\x08my_model\x12\x32\n\x0broot_object\x18\x01 \x01(\x0b\x32\x1d.my_model.root_object_message\x12\x0c\n\x04tag1\x18\x02 \x01(\x02\x12\x0c\n\x04tag2\x18\x03 \x01(\x05\x1a~\n\x13root_object_message\x12\x0c\n\x04tag4\x18\x01 \x01(\x08\x12:\n\x05inner\x18\x02 \x01(\x0b\x32+.my_model.root_object_message.inner_message\x1a\x1d\n\rinner_message\x12\x0c\n\x04tag3\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_proto_file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MY_MODEL']._serialized_start=31
  _globals['_MY_MODEL']._serialized_end=249
  _globals['_MY_MODEL_ROOT_OBJECT_MESSAGE']._serialized_start=123
  _globals['_MY_MODEL_ROOT_OBJECT_MESSAGE']._serialized_end=249
  _globals['_MY_MODEL_ROOT_OBJECT_MESSAGE_INNER_MESSAGE']._serialized_start=220
  _globals['_MY_MODEL_ROOT_OBJECT_MESSAGE_INNER_MESSAGE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
