# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generated_proto_file_manual.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'generated_proto_file_manual.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!generated_proto_file_manual.proto\"2\n\x0broot_object\x12\x15\n\x05inner\x18\x01 \x01(\x0b\x32\x06.inner\x12\x0c\n\x04tag4\x18\x02 \x01(\x08\"\x15\n\x05inner\x12\x0c\n\x04tag3\x18\x01 \x01(\t\"I\n\x08my_model\x12!\n\x0broot_object\x18\x01 \x01(\x0b\x32\x0c.root_object\x12\x0c\n\x04tag1\x18\x02 \x01(\x02\x12\x0c\n\x04tag2\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generated_proto_file_manual_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOT_OBJECT']._serialized_start=37
  _globals['_ROOT_OBJECT']._serialized_end=87
  _globals['_INNER']._serialized_start=89
  _globals['_INNER']._serialized_end=110
  _globals['_MY_MODEL']._serialized_start=112
  _globals['_MY_MODEL']._serialized_end=185
# @@protoc_insertion_point(module_scope)
