# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_model_config.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'data_model_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tag_config_pb2 as tag__config__pb2
from . import type_pb2 as type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61ta_model_config.proto\x1a\x10tag_config.proto\x1a\ntype.proto\"p\n\x0f\x44\x61taModelConfig\x12\x1c\n\x04type\x18\x01 \x01(\x0b\x32\x0e.DataModelType\x12\x14\n\x0c\x65xtends_path\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\x12\x18\n\x04tags\x18\x04 \x03(\x0b\x32\n.TagConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_model_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAMODELCONFIG']._serialized_start=57
  _globals['_DATAMODELCONFIG']._serialized_end=169
# @@protoc_insertion_point(module_scope)
