# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_object_config.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'data_object_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import type_pb2 as type__pb2
from . import data_model_config_pb2 as data__model__config__pb2
from . import props_pb2 as props__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x61ta_object_config.proto\x1a\ntype.proto\x1a\x17\x64\x61ta_model_config.proto\x1a\x0bprops.proto\"\x84\x01\n\x10\x44\x61taObjectConfig\x12 \n\x0b\x62\x61se_config\x18\x01 \x01(\x0e\x32\t.BaseTypeH\x00\x12-\n\x11\x64\x61ta_model_config\x18\x02 \x01(\x0b\x32\x10.DataModelConfigH\x00\x12\x15\n\x05props\x18\x03 \x01(\x0b\x32\x06.PropsB\x08\n\x06\x63onfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_object_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAOBJECTCONFIG']._serialized_start=79
  _globals['_DATAOBJECTCONFIG']._serialized_end=211
# @@protoc_insertion_point(module_scope)
