# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meta.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'meta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import method_pb2 as method__pb2
from . import tag_pb2 as tag__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmeta.proto\x1a\x0cmethod.proto\x1a\ttag.proto\"e\n\x04Meta\x12\x15\n\x08tracking\x18\x07 \x01(\x08H\x00\x88\x01\x01\x12\x0b\n\x03key\x18\x08 \x01(\t\x12\x12\n\x04tags\x18\t \x03(\x0b\x32\x04.Tag\x12\x18\n\x07methods\x18\n \x03(\x0b\x32\x07.MethodB\x0b\n\t_trackingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_META']._serialized_start=39
  _globals['_META']._serialized_end=140
# @@protoc_insertion_point(module_scope)
