# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: method_config.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'method_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import response_config_pb2 as response__config__pb2
from . import data_model_config_pb2 as data__model__config__pb2
from . import prop_pb2 as prop__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13method_config.proto\x1a\x15response_config.proto\x1a\x17\x64\x61ta_model_config.proto\x1a\nprop.proto\"w\n\x0cMethodConfig\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x1f\n\x06params\x18\x02 \x03(\x0b\x32\x0f.DataItemConfig\x12\"\n\tresponses\x18\x03 \x03(\x0b\x32\x0f.ResponseConfig\x12\x14\n\x05props\x18\x04 \x03(\x0b\x32\x05.Propb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'method_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METHODCONFIG']._serialized_start=83
  _globals['_METHODCONFIG']._serialized_end=202
# @@protoc_insertion_point(module_scope)
