# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: method.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'method.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tag_data_pb2 as tag__data__pb2
from . import prop_pb2 as prop__pb2
from . import param_pb2 as param__pb2
from . import body_pb2 as body__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmethod.proto\x1a\x0etag_data.proto\x1a\nprop.proto\x1a\x0bparam.proto\x1a\nbody.proto\"\xe8\x01\n\x06Method\x12\x0c\n\x04path\x18\x01 \x01(\t\x12!\n\x05props\x18\x02 \x03(\x0b\x32\x12.Method.PropsEntry\x12#\n\x06params\x18\x03 \x03(\x0b\x32\x13.Method.ParamsEntry\x12\x1c\n\tresponses\x18\x04 \x03(\x0b\x32\t.Response\x1a\x33\n\nPropsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Prop:\x02\x38\x01\x1a\x35\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Param:\x02\x38\x01\"\xc9\x01\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12#\n\x05props\x18\x03 \x03(\x0b\x32\x14.Response.PropsEntry\x12!\n\x04\x62ody\x18\x04 \x03(\x0b\x32\x13.Response.BodyEntry\x1a\x33\n\nPropsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Prop:\x02\x38\x01\x1a\x32\n\tBodyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Body:\x02\x38\x01\"x\n\x0fMethodQueryData\x12,\n\x06params\x18\x01 \x03(\x0b\x32\x1c.MethodQueryData.ParamsEntry\x1a\x37\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.TagData:\x02\x38\x01\"\x98\x01\n\x0cResponseData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12%\n\x04\x62ody\x18\x02 \x03(\x0b\x32\x17.ResponseData.BodyEntry\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x00\x88\x01\x01\x1a\x35\n\tBodyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.TagData:\x02\x38\x01\x42\x08\n\x06_errorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'method_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METHOD_PROPSENTRY']._loaded_options = None
  _globals['_METHOD_PROPSENTRY']._serialized_options = b'8\001'
  _globals['_METHOD_PARAMSENTRY']._loaded_options = None
  _globals['_METHOD_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSE_PROPSENTRY']._loaded_options = None
  _globals['_RESPONSE_PROPSENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSE_BODYENTRY']._loaded_options = None
  _globals['_RESPONSE_BODYENTRY']._serialized_options = b'8\001'
  _globals['_METHODQUERYDATA_PARAMSENTRY']._loaded_options = None
  _globals['_METHODQUERYDATA_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSEDATA_BODYENTRY']._loaded_options = None
  _globals['_RESPONSEDATA_BODYENTRY']._serialized_options = b'8\001'
  _globals['_METHOD']._serialized_start=70
  _globals['_METHOD']._serialized_end=302
  _globals['_METHOD_PROPSENTRY']._serialized_start=196
  _globals['_METHOD_PROPSENTRY']._serialized_end=247
  _globals['_METHOD_PARAMSENTRY']._serialized_start=249
  _globals['_METHOD_PARAMSENTRY']._serialized_end=302
  _globals['_RESPONSE']._serialized_start=305
  _globals['_RESPONSE']._serialized_end=506
  _globals['_RESPONSE_PROPSENTRY']._serialized_start=196
  _globals['_RESPONSE_PROPSENTRY']._serialized_end=247
  _globals['_RESPONSE_BODYENTRY']._serialized_start=456
  _globals['_RESPONSE_BODYENTRY']._serialized_end=506
  _globals['_METHODQUERYDATA']._serialized_start=508
  _globals['_METHODQUERYDATA']._serialized_end=628
  _globals['_METHODQUERYDATA_PARAMSENTRY']._serialized_start=573
  _globals['_METHODQUERYDATA_PARAMSENTRY']._serialized_end=628
  _globals['_RESPONSEDATA']._serialized_start=631
  _globals['_RESPONSEDATA']._serialized_end=783
  _globals['_RESPONSEDATA_BODYENTRY']._serialized_start=720
  _globals['_RESPONSEDATA_BODYENTRY']._serialized_end=773
# @@protoc_insertion_point(module_scope)
