# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prop.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'prop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tag_data_pb2 as tag__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nprop.proto\x1a\x0etag_data.proto\"8\n\x04Prop\x12\x17\n\x04type\x18\x07 \x01(\x0e\x32\t.DataType\x12\x17\n\x05value\x18\x08 \x01(\x0b\x32\x08.TagDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROP']._serialized_start=30
  _globals['_PROP']._serialized_end=86
# @@protoc_insertion_point(module_scope)
