# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: response_config.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'response_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import data_model_config_pb2 as data__model__config__pb2
from . import prop_pb2 as prop__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15response_config.proto\x1a\x17\x64\x61ta_model_config.proto\x1a\nprop.proto\"p\n\x0eResponseConfig\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.ResponseType\x12\x1d\n\x04\x62ody\x18\x03 \x03(\x0b\x32\x0f.DataItemConfig\x12\x14\n\x05props\x18\x04 \x03(\x0b\x32\x05.Prop*)\n\x0cResponseType\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03\x45RR\x10\x01\x12\x08\n\x04INFO\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSETYPE']._serialized_start=176
  _globals['_RESPONSETYPE']._serialized_end=217
  _globals['_RESPONSECONFIG']._serialized_start=62
  _globals['_RESPONSECONFIG']._serialized_end=174
# @@protoc_insertion_point(module_scope)
