# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: subnode.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'subnode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import method_pb2 as method__pb2
from . import tag_pb2 as tag__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsubnode.proto\x1a\x0cmethod.proto\x1a\ttag.proto\"a\n\x07Subnode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x04tags\x18\x02 \x03(\x0b\x32\x04.Tag\x12\x18\n\x07methods\x18\x03 \x03(\x0b\x32\x07.Method\x12\x1a\n\x08subnodes\x18\x04 \x03(\x0b\x32\x08.Subnodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subnode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBNODE']._serialized_start=42
  _globals['_SUBNODE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
