# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tag_config.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'tag_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import props_pb2 as props__pb2
from . import type_pb2 as type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tag_config.proto\x1a\x0bprops.proto\x1a\ntype.proto\"\x83\x01\n\tTagConfig\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x13\n\x04type\x18\x02 \x01(\x0b\x32\x05.Type\x12\x15\n\x05props\x18\x04 \x01(\x0b\x32\x06.Props\x12\x10\n\x08writable\x18\x05 \x01(\x08\x12*\n\tresponses\x18\x06 \x03(\x0b\x32\x17.TagWriteResponseConfig\"=\n\x16TagWriteResponseConfig\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x15\n\x05props\x18\x02 \x01(\x0b\x32\x06.Propsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAGCONFIG']._serialized_start=46
  _globals['_TAGCONFIG']._serialized_end=177
  _globals['_TAGWRITERESPONSECONFIG']._serialized_start=179
  _globals['_TAGWRITERESPONSECONFIG']._serialized_end=240
# @@protoc_insertion_point(module_scope)
