# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tag_group_session.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'tag_group_session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_data_pb2 as base__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17tag_group_session.proto\x1a\x0f\x62\x61se_data.proto\"e\n\x08TagGroup\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.TagGroup.DataEntry\x1a\x36\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.BaseData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_group_session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAGGROUP_DATAENTRY']._loaded_options = None
  _globals['_TAGGROUP_DATAENTRY']._serialized_options = b'8\001'
  _globals['_TAGGROUP']._serialized_start=44
  _globals['_TAGGROUP']._serialized_end=145
  _globals['_TAGGROUP_DATAENTRY']._serialized_start=91
  _globals['_TAGGROUP_DATAENTRY']._serialized_end=145
# @@protoc_insertion_point(module_scope)
