# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tag_config.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'tag_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import data_model_config_pb2 as data__model__config__pb2
from . import response_config_pb2 as response__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tag_config.proto\x1a\x17\x64\x61ta_model_config.proto\x1a\x15response_config.proto\"\x7f\n\tTagConfig\x12$\n\x0b\x64\x61ta_config\x18\x01 \x03(\x0b\x32\x0f.DataItemConfig\x12%\n\x0cwrite_config\x18\x02 \x03(\x0b\x32\x0f.TagWriteConfig\x12%\n\x0cgroup_config\x18\x03 \x03(\x0b\x32\x0f.TagGroupConfig\"B\n\x0eTagWriteConfig\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\"\n\tresponses\x18\x02 \x03(\x0b\x32\x0f.ResponseConfig\"c\n\x0eTagGroupConfig\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x10\n\x08writable\x18\x03 \x01(\x08\x12\"\n\tresponses\x18\x04 \x03(\x0b\x32\x0f.ResponseConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAGCONFIG']._serialized_start=68
  _globals['_TAGCONFIG']._serialized_end=195
  _globals['_TAGWRITECONFIG']._serialized_start=197
  _globals['_TAGWRITECONFIG']._serialized_end=263
  _globals['_TAGGROUPCONFIG']._serialized_start=265
  _globals['_TAGGROUPCONFIG']._serialized_end=364
# @@protoc_insertion_point(module_scope)
