# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: type.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntype.proto\">\n\x0c\x44\x61taModelRef\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x14\n\x07version\x18\x02 \x01(\rH\x00\x88\x01\x01\x42\n\n\x08_version\"W\n\x04Type\x12\x1e\n\tbase_type\x18\x01 \x01(\x0e\x32\t.BaseTypeH\x00\x12\'\n\x0e\x64\x61ta_model_ref\x18\x02 \x01(\x0b\x32\r.DataModelRefH\x00\x42\x06\n\x04type*\x98\x01\n\x08\x42\x61seType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03INT\x10\x01\x12\x08\n\x04LONG\x10\x02\x12\t\n\x05\x46LOAT\x10\x03\x12\n\n\x06STRING\x10\x04\x12\x08\n\x04\x42OOL\x10\x05\x12\x0c\n\x08LIST_INT\x10\x06\x12\r\n\tLIST_LONG\x10\x07\x12\x0e\n\nLIST_FLOAT\x10\x08\x12\x0f\n\x0bLIST_STRING\x10\t\x12\r\n\tLIST_BOOL\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASETYPE']._serialized_start=168
  _globals['_BASETYPE']._serialized_end=320
  _globals['_DATAMODELREF']._serialized_start=14
  _globals['_DATAMODELREF']._serialized_end=76
  _globals['_TYPE']._serialized_start=78
  _globals['_TYPE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
